SET SERVEROUTPUT ON;

--CRIANDO UMA FUNÇÃO
CREATE OR REPLACE FUNCTION CALCULA_FGTS (P_VALOR_VAL NUMBER)
RETURN NUMBER IS
BEGIN
    RETURN P_VALOR_VAL * 0.08;
END CALCULA_FGTS;


--CRIANDO UMA PROCEDURE E USANDO A FUNÇÃO ANTERIOR
CREATE OR REPLACE PROCEDURE PROCEDURE_FGTS IS
V_VALOR NUMBER;
BEGIN
V_VALOR := CALCULA_FGTS(5000);
DBMS_OUTPUT.PUT_LINE('O VALO DOR FGTS É: ' || TO_CHAR(V_VALOR));
END PROCEDURE_FGTS;

--EXECUTANDO A PROCEDURE
EXEC PROCEDURE_FGTS();
CALL PROCEDURE_FGTS();
EXECUTE PROCEDURE_FGTS();
BEGIN
PROCEDURE_FGTS();
END;